    steps:    
      - name: Check out source code
        uses: actions/checkout@v4  
      - name: Run ScanCentral SAST & Debricked scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
          debricked-sca-scan: false
        env:
          SSC_URL: ${{vars.SSC_URL}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          # SSC_LOGIN_EXTRA_OPTS: --socket-timeout=60s
          SC_SAST_TOKEN: ${{secrets.SC_SAST_CLIENT_AUTH_TOKEN}}
          # SC_SAST_LOGIN_EXTRA_OPTS: --socket-timeout=60s
          DEBRICKED_TOKEN: ${{secrets.DEBRICKED_TOKEN}}
          SSC_APPVERSION: TestLuis_GithubPython:v01
          # DO_SETUP: true
          # SETUP_ACTION: https://scm.my.org/shared-repos/fcli-actions/setup.yaml
          # SETUP_EXTRA_OPTS: --on-unsigned=ignore
          # SC_CLIENT_VERSION: 24.2
          # DO_PACKAGE_DEBUG: true
          # PACKAGE_EXTRA_OPTS: -oss -bt mvn
          SC_SAST_SENSOR_VERSION: 24.4.0
          # EXTRA_SC_SAST_SCAN_OPTS: 
          # DO_WAIT: true
          # DO_POLICY_CHECK: true
          # POLICY_CHECK_ACTION: https://scm.my.org/shared-repos/fcli-actions/check-policy.yaml
          # POLICY_CHECK_EXTRA_OPTS: --on-unsigned=ignore
          # DO_JOB_SUMMARY: true
          # JOB_SUMMARY_ACTION: https://scm.my.org/shared-repos/fcli-actions/job-summary.yaml
          # JOB_SUMMARY_EXTRA_OPTS: --on-unsigned=ignore
          # DO_PR_COMMENT: true
          # PR_COMMENT_ACTION: https://scm.my.org/shared-repos/fcli-actions/github-pr-comment.yaml
          # PR_COMMENT_EXTRA_OPTS: --on-unsigned=ignore
          # DO_EXPORT: true
          # EXPORT_ACTION: https://scm.my.org/shared-repos/fcli-actions/github-sast-report.yaml
          # EXPORT_EXTRA_OPTS: --on-unsigned=ignore
          # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip

name: 'Perform SAST scan'
description: 'Perform a SAST scan on ScanCentral SAST'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: fortify/github-action/internal/set-ssc-var-defaults@main
    - uses: fortify/github-action/setup@main
      with:
        export-path: false
        fcli: action-default
        debricked-cli: ${{ env.DO_DEBRICKED_SCAN=='true' && 'action-default' || 'skip' }}
    - uses: fortify/github-action/internal/ssc-login@main
    - uses: fortify/github-action/internal/sc-sast-login@main
    - uses: fortify/github-action/package@main
    - uses: fortify/github-action/internal/run-script@main
      with:
        script: sc-sast-and-debricked-scan.sh
      env: 
        DO_SC_SAST_SCAN: true
        GITHUB_TOKEN: ${{ github.token }}
    - if: env.DO_EXPORT == 'true'
      uses: fortify/github-action/ssc-export@main
        
branding:
  icon: 'shield'
  color: 'blue'

